// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/9/2025, 7:56:29 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg3 from "./../storefront-ui.tailwind-config.mjs";
const config = [
{"content":{"files":["C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/plugins/**/*.{js,ts,mjs}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/composables/**/*.{js,ts,mjs}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/utils/**/*.{js,ts,mjs}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/company-app/app/app.config.{js,ts,mjs}"]}},
{"content":["./node_modules/@storefront-ui/vue/**/*.{js,mjs}"]},
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;